# blair/cf/config/overall.yaml

seed: 101 # According to original authors

data_path: ./cache/cf
benchmark_filename: [train, valid, test]
train_neg_sample_args: ~

topk: [20, 50]
metrics: [Recall, NDCG]
valid_metric: Recall@20
eval_batch_size: 409600000
stopping_step: 20
